export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_PENDING = 'FETCH_PHOTOS_PENDING';
export const FETCH_PHOTOS_FULFILLED = 'FETCH_PHOTOS_FULFILLED';
export const FETCH_PHOTOS_REJECTED = 'FETCH_PHOTOS_REJECTED';

export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const UPLOAD_PHOTO_PENDING = 'UPLOAD_PHOTO_PENDING';
export const UPLOAD_PHOTO_FULFILLED = 'UPLOAD_PHOTO_FULFILLED';
export const UPLOAD_PHOTO_REJECTED = 'UPLOAD_PHOTO_REJECTED';

export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_PHOTO_PENDING = 'DELETE_PHOTO_PENDING';
export const DELETE_PHOTO_FULFILLED = 'DELETE_PHOTO_FULFILLED';
export const DELETE_PHOTO_REJECTED = 'DELETE_PHOTO_REJECTED';

export const SHOW_FORM = 'SHOW_FORM';
export const HIDE_FORM = 'HIDE_FORM';
